# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI v2

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install imagemagick libmagick++-dev ghostscript node-gyp
    - name: check imagemagick version
      run: apt show imagemagick | grep Version | cut -d':' -f3 | cut -d'+' -f1 | sed 's/^/v/'
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Npm install
      run: npm i
    - name: Build
      run: npm run build
    - name: Install Arial font for test
      run: |
        mkdir -p /usr/share/fonts/truetype/windows
        cp ./test/fonts/* /usr/share/fonts/truetype/windows/
    - name: Run test
      run: npm run test
      continue-on-error: true
    - uses: actions/upload-artifact@v3
      with:
        name: "v2-build"
        path: |
          ./
          !./node_modules
    
